name = "ScenarioTrees"
uuid = "8b668c19-4850-4a9f-81bd-9b61cd78e389"
version = "1.0.0-DEV"
authors = ["Ruben <ruben.schlotter@gmail.com> and contributors"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "1.6.3"
CairoMakie = "0.15.8"
DataFrames = "1.8.1"
Distributions = "0.25.123"
LinearAlgebra = "1.12.0"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
